# config.py - Auto-generated by camel-pad, do not edit manually
# Re-generate with: camel-pad config-push

from adafruit_hid.keycode import Keycode

TIMING = {
    "double_press_window_ms": 300,
    "long_press_threshold_ms": 500,
}

BUTTONS = {
    0: {  # btn_a
        "press": [Keycode.CONTROL, Keycode.GRAVE_ACCENT],
        "double_press": [Keycode.GUI, Keycode.Z],
        "long_press": [[Keycode.Q], [Keycode.ENTER]],
    },
    1: {  # btn_b
        "press": [Keycode.DOWN_ARROW],
        "double_press": [Keycode.PAGE_DOWN],
        "long_press": [Keycode.END],
    },
    2: {  # btn_c
        "press": [Keycode.UP_ARROW],
        "double_press": [Keycode.PAGE_UP],
        "long_press": [Keycode.HOME],
    },
    3: {  # btn_d
        "press": [Keycode.ENTER],
        "double_press": [Keycode.TAB],
        "long_press": [Keycode.ESCAPE],
    },
}

